/* tslint:disable */


/**
 * AUTO-GENERATED FILE @ 2022-01-17 14:07:23 - DO NOT EDIT!
 *
 * This file was automatically generated by schemats v.3.0.3
 * $ schemats generate -c mysql://username:password@127.0.0.1/pueblo_2022 -t akce -t analyzy -t digitalizace_nalez -t digitalizace_plany -t dopisy_seznam -t faktury -t geodet_body -t geodet_plany -t kresleni_foto -t migrations -t nz_word -t oauth_access_tokens -t oauth_auth_codes -t oauth_clients -t oauth_personal_access_clients -t oauth_refresh_tokens -t pueblo_users -t pueblo_users_dopisy -t pueblo_users_role -t pueblo_users_role_dopisy -t teren_foto -t teren_negativni_foto -t teren_scan -t updates -t users -s pueblo_2022
 *
 */

export type enum_type = 'created' | 'updated' | 'deleted';

export namespace akceFields {
    export type id_akce = number;
    export type c_akce = string | null;
    export type cislo_per_year = number | null;
    export type rok_per_year = number | null;
    export type nazev_akce = string | null;
    export type nazev_akce_final = number | null;
    export type objednavka = number | null;
    export type objednavka_cislo = string | null;
    export type objednavka_info = string | null;
    export type smlouva = number | null;
    export type smlouva_info = string | null;
    export type rozpocet_A = number | null;
    export type rozpocet_A_final = number | null;
    export type fakturovano_A = number | null;
    export type rozpocet_B = number | null;
    export type rozpocet_B_final = number | null;
    export type fakturovano_B = number | null;
    export type registrovano_bit = number | null;
    export type registrace_info = string | null;
    export type id_stav = number | null;
    export type investor_jmeno = string | null;
    export type investor_kontakt = string | null;
    export type investor_adresa = string | null;
    export type investor_ico = string | null;
    export type katastr = string | null;
    export type okres = string | null;
    export type nalez = number | null;
    export type datum_pocatku_text = string | null;
    export type datum_pocatku = Date | null;
    export type datum_ukonceni = Date | null;
    export type user_id = number | null;
    export type datum_ukonceni_text = string | null;
    export type kraj = string | null;
    export type zaa = string | null;
    export type zaa_hlaseno = number | null;
    export type nz_vlozil = number | null;
    export type nz_vlozeno = Date | null;
    export type zaa_vlozil = number | null;
    export type zaa_vlozeno = Date | null;
    export type NZ = string | null;
    export type NZ_vytvoril = string | null;
    export type hotovo = number | null;
    export type datum_vytvoreni = Date;
    export type EL_GPS_1_N = string | null;
    export type EL_GPS_1_E = string | null;
    export type EL_GPS_2_N = string | null;
    export type EL_GPS_2_E = string | null;
    export type EL_Termin = string | null;
    export type EL_Forma = string | null;
    export type EL_Denik = string | null;
    export type EL_Dokumentovane = Buffer | null;
    export type EL_Movite = Buffer | null;
    export type EL_Popis = Buffer | null;
    export type EL_hotovo = number | null;
    export type EL_fotodokumentace = string | null;
    export type EL_kresebna_a_textova = string | null;
    export type EL_ulozeni = string | null;
    export type teren_databaze = string | null;
    export type teren_databaze_vlozil = number | null;
    export type teren_databaze_vlozeno = Date | null;
    export type LAB_umyto = number | null;
    export type LAB_popsano = number | null;
    export type LAB_datovano = number | null;
    export type LAB_databaze = string | null;
    export type EL_datum = string | null;
    export type LAB_databaze_vlozil = number | null;
    export type LAB_databaze_vlozeno = Date | null;
    export type LAB_hotovo = number | null;
    export type KR_vybrano = number | null;
    export type KR_hotovo = number | null;
    export type EL_lokalita = string | null;
    export type TER_hotovo = number | null;
    export type DIG_hotovo = number | null;
    export type GEO_hotovo = number | null;
    export type ANA_hotovo = number | null;
    export type NZW_hotovo = number | null;
    export type hotovo_datum = Date | null;

}

export interface akce {
    id_akce: akceFields.id_akce;
    c_akce: akceFields.c_akce;
    cislo_per_year: akceFields.cislo_per_year;
    rok_per_year: akceFields.rok_per_year;
    nazev_akce: akceFields.nazev_akce;
    nazev_akce_final: akceFields.nazev_akce_final;
    objednavka: akceFields.objednavka;
    objednavka_cislo: akceFields.objednavka_cislo;
    objednavka_info: akceFields.objednavka_info;
    smlouva: akceFields.smlouva;
    smlouva_info: akceFields.smlouva_info;
    rozpocet_A: akceFields.rozpocet_A;
    rozpocet_A_final: akceFields.rozpocet_A_final;
    fakturovano_A: akceFields.fakturovano_A;
    rozpocet_B: akceFields.rozpocet_B;
    rozpocet_B_final: akceFields.rozpocet_B_final;
    fakturovano_B: akceFields.fakturovano_B;
    registrovano_bit: akceFields.registrovano_bit;
    registrace_info: akceFields.registrace_info;
    id_stav: akceFields.id_stav;
    investor_jmeno: akceFields.investor_jmeno;
    investor_kontakt: akceFields.investor_kontakt;
    investor_adresa: akceFields.investor_adresa;
    investor_ico: akceFields.investor_ico;
    katastr: akceFields.katastr;
    okres: akceFields.okres;
    nalez: akceFields.nalez;
    datum_pocatku_text: akceFields.datum_pocatku_text;
    datum_pocatku: akceFields.datum_pocatku;
    datum_ukonceni: akceFields.datum_ukonceni;
    user_id: akceFields.user_id;
    datum_ukonceni_text: akceFields.datum_ukonceni_text;
    kraj: akceFields.kraj;
    zaa: akceFields.zaa;
    zaa_hlaseno: akceFields.zaa_hlaseno;
    nz_vlozil: akceFields.nz_vlozil;
    nz_vlozeno: akceFields.nz_vlozeno;
    zaa_vlozil: akceFields.zaa_vlozil;
    zaa_vlozeno: akceFields.zaa_vlozeno;
    NZ: akceFields.NZ;
    NZ_vytvoril: akceFields.NZ_vytvoril;
    hotovo: akceFields.hotovo;
    datum_vytvoreni: akceFields.datum_vytvoreni;
    EL_GPS_1_N: akceFields.EL_GPS_1_N;
    EL_GPS_1_E: akceFields.EL_GPS_1_E;
    EL_GPS_2_N: akceFields.EL_GPS_2_N;
    EL_GPS_2_E: akceFields.EL_GPS_2_E;
    EL_Termin: akceFields.EL_Termin;
    EL_Forma: akceFields.EL_Forma;
    EL_Denik: akceFields.EL_Denik;
    EL_Dokumentovane: akceFields.EL_Dokumentovane;
    EL_Movite: akceFields.EL_Movite;
    EL_Popis: akceFields.EL_Popis;
    EL_hotovo: akceFields.EL_hotovo;
    EL_fotodokumentace: akceFields.EL_fotodokumentace;
    EL_kresebna_a_textova: akceFields.EL_kresebna_a_textova;
    EL_ulozeni: akceFields.EL_ulozeni;
    teren_databaze: akceFields.teren_databaze;
    teren_databaze_vlozil: akceFields.teren_databaze_vlozil;
    teren_databaze_vlozeno: akceFields.teren_databaze_vlozeno;
    LAB_umyto: akceFields.LAB_umyto;
    LAB_popsano: akceFields.LAB_popsano;
    LAB_datovano: akceFields.LAB_datovano;
    LAB_databaze: akceFields.LAB_databaze;
    EL_datum: akceFields.EL_datum;
    LAB_databaze_vlozil: akceFields.LAB_databaze_vlozil;
    LAB_databaze_vlozeno: akceFields.LAB_databaze_vlozeno;
    LAB_hotovo: akceFields.LAB_hotovo;
    KR_vybrano: akceFields.KR_vybrano;
    KR_hotovo: akceFields.KR_hotovo;
    EL_lokalita: akceFields.EL_lokalita;
    TER_hotovo: akceFields.TER_hotovo;
    DIG_hotovo: akceFields.DIG_hotovo;
    GEO_hotovo: akceFields.GEO_hotovo;
    ANA_hotovo: akceFields.ANA_hotovo;
    NZW_hotovo: akceFields.NZW_hotovo;
    hotovo_datum: akceFields.hotovo_datum;

}

export namespace analyzyFields {
    export type id = number;
    export type file_path = string | null;
    export type id_akce = number | null;
    export type vlozil = string | null;
    export type vlozeno = Date;

}

export interface analyzy {
    id: analyzyFields.id;
    file_path: analyzyFields.file_path;
    id_akce: analyzyFields.id_akce;
    vlozil: analyzyFields.vlozil;
    vlozeno: analyzyFields.vlozeno;

}

export namespace digitalizace_nalezFields {
    export type id = number;
    export type file_path = string | null;
    export type id_akce = number | null;
    export type vlozil = string | null;
    export type vlozeno = Date;

}

export interface digitalizace_nalez {
    id: digitalizace_nalezFields.id;
    file_path: digitalizace_nalezFields.file_path;
    id_akce: digitalizace_nalezFields.id_akce;
    vlozil: digitalizace_nalezFields.vlozil;
    vlozeno: digitalizace_nalezFields.vlozeno;

}

export namespace digitalizace_planyFields {
    export type id = number;
    export type file_path = string | null;
    export type id_akce = number | null;
    export type vlozil = string | null;
    export type vlozeno = Date;

}

export interface digitalizace_plany {
    id: digitalizace_planyFields.id;
    file_path: digitalizace_planyFields.file_path;
    id_akce: digitalizace_planyFields.id_akce;
    vlozil: digitalizace_planyFields.vlozil;
    vlozeno: digitalizace_planyFields.vlozeno;

}

export namespace dopisy_seznamFields {
    export type id_dopis = number;
    export type kraj = string | null;
    export type vlozeno = Date;
    export type investor = string | null;
    export type objekt = string | null;
    export type katastralni_urad = string | null;
    export type datum_odeslani = string | null;
    export type text_reakce_inv = string | null;
    export type vyzkum = string | null;
    export type kontakt = string | null;
    export type stav = number | null;
    export type c_akce = string | null;
    export type id_vlozil = number | null;

}

export interface dopisy_seznam {
    id_dopis: dopisy_seznamFields.id_dopis;
    kraj: dopisy_seznamFields.kraj;
    vlozeno: dopisy_seznamFields.vlozeno;
    investor: dopisy_seznamFields.investor;
    objekt: dopisy_seznamFields.objekt;
    katastralni_urad: dopisy_seznamFields.katastralni_urad;
    datum_odeslani: dopisy_seznamFields.datum_odeslani;
    text_reakce_inv: dopisy_seznamFields.text_reakce_inv;
    vyzkum: dopisy_seznamFields.vyzkum;
    kontakt: dopisy_seznamFields.kontakt;
    stav: dopisy_seznamFields.stav;
    c_akce: dopisy_seznamFields.c_akce;
    id_vlozil: dopisy_seznamFields.id_vlozil;

}

export namespace fakturyFields {
    export type id_zaznam = number;
    export type c_akce = string | null;
    export type c_faktury = string | null;
    export type castka = number | null;
    export type typ_castky = number | null;
    export type datum_vlozeni = Date;
    export type info = string | null;
    export type akce_id = number | null;

}

export interface faktury {
    id_zaznam: fakturyFields.id_zaznam;
    c_akce: fakturyFields.c_akce;
    c_faktury: fakturyFields.c_faktury;
    castka: fakturyFields.castka;
    typ_castky: fakturyFields.typ_castky;
    datum_vlozeni: fakturyFields.datum_vlozeni;
    info: fakturyFields.info;
    akce_id: fakturyFields.akce_id;

}

export namespace geodet_bodyFields {
    export type id = number;
    export type file_path = string | null;
    export type id_akce = number | null;
    export type vlozil = string | null;
    export type vlozeno = Date;

}

export interface geodet_body {
    id: geodet_bodyFields.id;
    file_path: geodet_bodyFields.file_path;
    id_akce: geodet_bodyFields.id_akce;
    vlozil: geodet_bodyFields.vlozil;
    vlozeno: geodet_bodyFields.vlozeno;

}

export namespace geodet_planyFields {
    export type id = number;
    export type file_path = string | null;
    export type id_akce = number | null;
    export type vlozil = string | null;
    export type vlozeno = Date;

}

export interface geodet_plany {
    id: geodet_planyFields.id;
    file_path: geodet_planyFields.file_path;
    id_akce: geodet_planyFields.id_akce;
    vlozil: geodet_planyFields.vlozil;
    vlozeno: geodet_planyFields.vlozeno;

}

export namespace kresleni_fotoFields {
    export type id = number;
    export type file_path = string | null;
    export type id_akce = number | null;
    export type vlozil = string | null;
    export type vlozeno = Date;

}

export interface kresleni_foto {
    id: kresleni_fotoFields.id;
    file_path: kresleni_fotoFields.file_path;
    id_akce: kresleni_fotoFields.id_akce;
    vlozil: kresleni_fotoFields.vlozil;
    vlozeno: kresleni_fotoFields.vlozeno;

}

export namespace migrationsFields {
    export type id = number;
    export type migration = string;
    export type batch = number;

}

export interface migrations {
    id: migrationsFields.id;
    migration: migrationsFields.migration;
    batch: migrationsFields.batch;

}

export namespace nz_wordFields {
    export type id = number;
    export type file_path = string | null;
    export type id_akce = number | null;
    export type vlozil = string | null;
    export type vlozeno = Date;

}

export interface nz_word {
    id: nz_wordFields.id;
    file_path: nz_wordFields.file_path;
    id_akce: nz_wordFields.id_akce;
    vlozil: nz_wordFields.vlozil;
    vlozeno: nz_wordFields.vlozeno;

}

export namespace oauth_access_tokensFields {
    export type id = string;
    export type user_id = number | null;
    export type client_id = number;
    export type name = string | null;
    export type scopes = string | null;
    export type revoked = boolean;
    export type created_at = Date | null;
    export type updated_at = Date | null;
    export type expires_at = Date | null;

}

export interface oauth_access_tokens {
    id: oauth_access_tokensFields.id;
    user_id: oauth_access_tokensFields.user_id;
    client_id: oauth_access_tokensFields.client_id;
    name: oauth_access_tokensFields.name;
    scopes: oauth_access_tokensFields.scopes;
    revoked: oauth_access_tokensFields.revoked;
    created_at: oauth_access_tokensFields.created_at;
    updated_at: oauth_access_tokensFields.updated_at;
    expires_at: oauth_access_tokensFields.expires_at;

}

export namespace oauth_auth_codesFields {
    export type id = string;
    export type user_id = number;
    export type client_id = number;
    export type scopes = string | null;
    export type revoked = boolean;
    export type expires_at = Date | null;

}

export interface oauth_auth_codes {
    id: oauth_auth_codesFields.id;
    user_id: oauth_auth_codesFields.user_id;
    client_id: oauth_auth_codesFields.client_id;
    scopes: oauth_auth_codesFields.scopes;
    revoked: oauth_auth_codesFields.revoked;
    expires_at: oauth_auth_codesFields.expires_at;

}

export namespace oauth_clientsFields {
    export type id = number;
    export type user_id = number | null;
    export type name = string;
    export type secret = string | null;
    export type redirect = string;
    export type personal_access_client = boolean;
    export type password_client = boolean;
    export type revoked = boolean;
    export type created_at = Date | null;
    export type updated_at = Date | null;

}

export interface oauth_clients {
    id: oauth_clientsFields.id;
    user_id: oauth_clientsFields.user_id;
    name: oauth_clientsFields.name;
    secret: oauth_clientsFields.secret;
    redirect: oauth_clientsFields.redirect;
    personal_access_client: oauth_clientsFields.personal_access_client;
    password_client: oauth_clientsFields.password_client;
    revoked: oauth_clientsFields.revoked;
    created_at: oauth_clientsFields.created_at;
    updated_at: oauth_clientsFields.updated_at;

}

export namespace oauth_personal_access_clientsFields {
    export type id = number;
    export type client_id = number;
    export type created_at = Date | null;
    export type updated_at = Date | null;

}

export interface oauth_personal_access_clients {
    id: oauth_personal_access_clientsFields.id;
    client_id: oauth_personal_access_clientsFields.client_id;
    created_at: oauth_personal_access_clientsFields.created_at;
    updated_at: oauth_personal_access_clientsFields.updated_at;

}

export namespace oauth_refresh_tokensFields {
    export type id = string;
    export type access_token_id = string;
    export type revoked = boolean;
    export type expires_at = Date | null;

}

export interface oauth_refresh_tokens {
    id: oauth_refresh_tokensFields.id;
    access_token_id: oauth_refresh_tokensFields.access_token_id;
    revoked: oauth_refresh_tokensFields.revoked;
    expires_at: oauth_refresh_tokensFields.expires_at;

}

export namespace pueblo_usersFields {
    export type id_user = number;
    export type username = string | null;
    export type password = string | null;
    export type jmeno = string | null;
    export type prijmeni = string | null;
    export type typ_uzivatele = string | null;
    export type datum_vytvoreni = Date;
    export type hints = number | null;
    export type last_login = Date;
    export type last_success = Date;
    export type active = number | null;

}

export interface pueblo_users {
    id_user: pueblo_usersFields.id_user;
    username: pueblo_usersFields.username;
    password: pueblo_usersFields.password;
    jmeno: pueblo_usersFields.jmeno;
    prijmeni: pueblo_usersFields.prijmeni;
    typ_uzivatele: pueblo_usersFields.typ_uzivatele;
    datum_vytvoreni: pueblo_usersFields.datum_vytvoreni;
    hints: pueblo_usersFields.hints;
    last_login: pueblo_usersFields.last_login;
    last_success: pueblo_usersFields.last_success;
    active: pueblo_usersFields.active;

}

export namespace pueblo_users_dopisyFields {
    export type id_user = number;
    export type username = string | null;
    export type password = string | null;
    export type jmeno = string | null;
    export type prijmeni = string | null;
    export type typ_uzivatele = string | null;
    export type datum_vytvoreni = Date;
    export type hints = number | null;
    export type last_login = Date;
    export type last_success = Date;
    export type active = number | null;

}

export interface pueblo_users_dopisy {
    id_user: pueblo_users_dopisyFields.id_user;
    username: pueblo_users_dopisyFields.username;
    password: pueblo_users_dopisyFields.password;
    jmeno: pueblo_users_dopisyFields.jmeno;
    prijmeni: pueblo_users_dopisyFields.prijmeni;
    typ_uzivatele: pueblo_users_dopisyFields.typ_uzivatele;
    datum_vytvoreni: pueblo_users_dopisyFields.datum_vytvoreni;
    hints: pueblo_users_dopisyFields.hints;
    last_login: pueblo_users_dopisyFields.last_login;
    last_success: pueblo_users_dopisyFields.last_success;
    active: pueblo_users_dopisyFields.active;

}

export namespace pueblo_users_roleFields {
    export type id_role = number;
    export type nazev = string | null;
    export type vlozil = string | null;
    export type vlozeno = Date;

}

export interface pueblo_users_role {
    id_role: pueblo_users_roleFields.id_role;
    nazev: pueblo_users_roleFields.nazev;
    vlozil: pueblo_users_roleFields.vlozil;
    vlozeno: pueblo_users_roleFields.vlozeno;

}

export namespace pueblo_users_role_dopisyFields {
    export type id_role = number;
    export type nazev = string | null;
    export type vlozil = string | null;
    export type vlozeno = Date;

}

export interface pueblo_users_role_dopisy {
    id_role: pueblo_users_role_dopisyFields.id_role;
    nazev: pueblo_users_role_dopisyFields.nazev;
    vlozil: pueblo_users_role_dopisyFields.vlozil;
    vlozeno: pueblo_users_role_dopisyFields.vlozeno;

}

export namespace teren_fotoFields {
    export type id = number;
    export type file_path = string | null;
    export type id_akce = number | null;
    export type vlozil = string | null;
    export type vlozeno = Date;

}

export interface teren_foto {
    id: teren_fotoFields.id;
    file_path: teren_fotoFields.file_path;
    id_akce: teren_fotoFields.id_akce;
    vlozil: teren_fotoFields.vlozil;
    vlozeno: teren_fotoFields.vlozeno;

}

export namespace teren_negativni_fotoFields {
    export type id = number;
    export type file_path = string | null;
    export type id_akce = number | null;
    export type vlozil = string | null;
    export type vlozeno = Date;

}

export interface teren_negativni_foto {
    id: teren_negativni_fotoFields.id;
    file_path: teren_negativni_fotoFields.file_path;
    id_akce: teren_negativni_fotoFields.id_akce;
    vlozil: teren_negativni_fotoFields.vlozil;
    vlozeno: teren_negativni_fotoFields.vlozeno;

}

export namespace teren_scanFields {
    export type id = number;
    export type file_path = string | null;
    export type id_akce = number | null;
    export type vlozil = string | null;
    export type vlozeno = Date;

}

export interface teren_scan {
    id: teren_scanFields.id;
    file_path: teren_scanFields.file_path;
    id_akce: teren_scanFields.id_akce;
    vlozil: teren_scanFields.vlozil;
    vlozeno: teren_scanFields.vlozeno;

}

export namespace updatesFields {
    export type id = number;
    export type akce_id = number;
    export type user_id = number;
    export type type = enum_type;
    export type description = string;
    export type created_at = Date;

}

export interface updates {
    id: updatesFields.id;
    akce_id: updatesFields.akce_id;
    user_id: updatesFields.user_id;
    type: updatesFields.type;
    description: updatesFields.description;
    created_at: updatesFields.created_at;

}

export namespace usersFields {
    export type id = number;
    export type user_name = string;
    export type full_name = string;
    export type email = string | null;
    export type email_verified_at = Date | null;
    export type password = string;
    export type remember_token = string | null;
    export type created_at = Date | null;
    export type updated_at = Date | null;
    export type typ_uzivatele = string | null;
    export type role = number | null;
    export type active = number | null;

}

export interface users {
    id: usersFields.id;
    user_name: usersFields.user_name;
    full_name: usersFields.full_name;
    email: usersFields.email;
    email_verified_at: usersFields.email_verified_at;
    password: usersFields.password;
    remember_token: usersFields.remember_token;
    created_at: usersFields.created_at;
    updated_at: usersFields.updated_at;
    typ_uzivatele: usersFields.typ_uzivatele;
    role: usersFields.role;
    active: usersFields.active;

}
